version: 2

sources:

    - name: CRM
      schema: default
      tags: ["CRM"]      
      loader: S3
      description: "sales data stored in S3"

      tables:
        - name: sales
          description: "sales"
          identifier: src_v_sales

