version: 2

sources:

    - name: dbgen
      schema: default
      tags: ["dbgen"]      
      loader: S3
      description: "sales data stored in S3"

      tables:

        - name: sales
          description: "sales"
          identifier: src_v_sales

