
version: 2

models:

    - name: stg_sales
      columns:
        - name: sale_id
          description: ""
          tests:
            - unique
            - not_null
          name: user_id
          description: ""
          tests:
            - not_null
          name: sale_date
          description: ""
          tests:
            - not_null 